// Esta es tu lista ampliada de nombres de colores con más de 600 colores
// Organizados por categorías para mejor referencia

export const colorNameList = [
  // Colores básicos y neutros
  { name: "Negro", hex: "#000000" },
  { name: "Blanco", hex: "#FFFFFF" },
  { name: "Blanco Fantasma", hex: "#F8F8FF" },
  { name: "Blanco Humo", hex: "#F5F5F5" },
  { name: "Blanco Navajo", hex: "#FFDEAD" },
  { name: "Blanco Almendra", hex: "#FFEBCD" },
  { name: "Marfil", hex: "#FFFFF0" },
  { name: "Gris", hex: "#808080" },
  { name: "Gris Claro", hex: "#D3D3D3" },
  { name: "Gris Plata", hex: "#C0C0C0" },
  { name: "Gris Oscuro", hex: "#A9A9A9" },
  { name: "Gris Pizarra", hex: "#708090" },
  { name: "Gris Pizarra Claro", hex: "#778899" },
  { name: "Gris Pizarra Oscuro", hex: "#2F4F4F" },
  { name: "Gris Gainsboro", hex: "#DCDCDC" },
  { name: "Gris Tenue", hex: "#696969" },

  // Rojos y Rosados
  { name: "Rojo", hex: "#FF0000" },
  { name: "Rojo Oscuro", hex: "#8B0000" },
  { name: "Rojo Carmesí", hex: "#DC143C" },
  { name: "Rojo Fuego", hex: "#B22222" },
  { name: "Rojo Ladrillo", hex: "#B22222" },
  { name: "Rojo Tomate", hex: "#FF6347" },
  { name: "Rojo Coral", hex: "#FF7F50" },
  { name: "Rojo Salmon", hex: "#FA8072" },
  { name: "Rojo Salmon Claro", hex: "#FFA07A" },
  { name: "Rojo Salmon Oscuro", hex: "#E9967A" },
  { name: "Rojo Indio", hex: "#CD5C5C" },
  { name: "Rojo Chino", hex: "#AA381E" },
  { name: "Rojo Cardenal", hex: "#C41E3A" },
  { name: "Rojo Cadmio", hex: "#E30022" },
  { name: "Rojo Ferrari", hex: "#FF2800" },
  { name: "Rojo Escarlata", hex: "#FF2400" },
  { name: "Rojo Rubí", hex: "#E0115F" },
  { name: "Rojo Granate", hex: "#800000" },
  { name: "Rojo Burdeos", hex: "#800020" },
  { name: "Rojo Mahogany", hex: "#C04000" },
  { name: "Rojo Óxido", hex: "#B7410E" },
  { name: "Rosa", hex: "#FFC0CB" },
  { name: "Rosa Claro", hex: "#FFB6C1" },
  { name: "Rosa Caliente", hex: "#FF69B4" },
  { name: "Rosa Fuerte", hex: "#FF1493" },
  { name: "Rosa Profundo", hex: "#FF1493" },
  { name: "Rosa Medio", hex: "#DB7093" },
  { name: "Rosa Pálido", hex: "#FADADD" },
  { name: "Rosa Lavanda", hex: "#FFF0F5" },
  { name: "Rosa Brumoso", hex: "#FFE4E1" },
  { name: "Rosa Antiguo", hex: "#C08081" },
  { name: "Rosa Coral", hex: "#F88379" },
  { name: "Rosa Fucsia", hex: "#FF00FF" },
  { name: "Rosa Magenta", hex: "#FF00FF" },
  { name: "Rosa Magenta Oscuro", hex: "#8B008B" },
  { name: "Rosa Orquídea", hex: "#DA70D6" },
  { name: "Rosa Orquídea Medio", hex: "#BA55D3" },
  { name: "Rosa Orquídea Oscuro", hex: "#9932CC" },
  { name: "Rosa Violeta", hex: "#C71585" },
  { name: "Rosa Cereza", hex: "#DE3163" },
  { name: "Rosa Barbie", hex: "#E0218A" },
  { name: "Rosa Chicle", hex: "#FFB7C5" },

  // Naranjas y Melocotones
  { name: "Naranja", hex: "#FFA500" },
  { name: "Naranja Oscuro", hex: "#FF8C00" },
  { name: "Naranja Rojo", hex: "#FF4500" },
  { name: "Naranja Coral", hex: "#FF7F50" },
  { name: "Naranja Tomate", hex: "#FF6347" },
  { name: "Naranja Zanahoria", hex: "#ED9121" },
  { name: "Naranja Mandarin", hex: "#F28500" },
  { name: "Naranja Calabaza", hex: "#FF7518" },
  { name: "Naranja Cobre", hex: "#B87333" },
  { name: "Naranja Cadmio", hex: "#FF6103" },
  { name: "Naranja Internacional", hex: "#FF4F00" },
  { name: "Naranja Princeton", hex: "#FF8F00" },
  { name: "Naranja UT", hex: "#FF8200" },
  { name: "Naranja Texas", hex: "#FF8200" },
  { name: "Naranja Siena", hex: "#A0522D" },
  { name: "Naranja Siena Quemado", hex: "#8A3324" },
  { name: "Melocotón", hex: "#FFE5B4" },
  { name: "Melocotón Claro", hex: "#FFDAB9" },
  { name: "Melocotón Oscuro", hex: "#FFDAB9" },
  { name: "Melocotón Puff", hex: "#FFDAB9" },
  { name: "Durazno", hex: "#FFE5B4" },
  { name: "Albaricoque", hex: "#FBCEB1" },
  { name: "Mango", hex: "#FF8243" },
  { name: "Papaya", hex: "#FFEFD5" },
  { name: "Cantalupo", hex: "#FFA474" },

  // Amarillos y Dorados
  { name: "Amarillo", hex: "#FFFF00" },
  { name: "Amarillo Claro", hex: "#FFFFE0" },
  { name: "Amarillo Maíz", hex: "#FFF8DC" },
  { name: "Amarillo Limón", hex: "#FFFACD" },
  { name: "Amarillo Limón Chiffon", hex: "#FFFACD" },
  { name: "Amarillo Pálido", hex: "#FFFFE0" },
  { name: "Amarillo Oro", hex: "#FFD700" },
  { name: "Amarillo Oro Oscuro", hex: "#B8860B" },
  { name: "Amarillo Oro Pálido", hex: "#EEE8AA" },
  { name: "Amarillo Nápoles", hex: "#FADA5E" },
  { name: "Amarillo Mantequilla", hex: "#FFFDD0" },
  { name: "Amarillo Crema", hex: "#FFFDD0" },
  { name: "Amarillo Flavescente", hex: "#F7E98E" },
  { name: "Amarillo Estroncio", hex: "#E4D00A" },
  { name: "Amarillo Mikado", hex: "#FFC40C" },
  { name: "Amarillo Safety", hex: "#EED202" },
  { name: "Amarillo Naranja", hex: "#FFAE42" },
  { name: "Amarillo Mostaza", hex: "#FFDB58" },
  { name: "Amarillo Ocre", hex: "#CC7722" },
  { name: "Amarillo Arena", hex: "#F4A460" },
  { name: "Caqui", hex: "#F0E68C" },
  { name: "Caqui Oscuro", hex: "#BDB76B" },
  { name: "Dorado", hex: "#FFD700" },
  { name: "Dorado Metálico", hex: "#D4AF37" },
  { name: "Dorado Web", hex: "#FFD700" },
  { name: "Dorado Viejo", hex: "#CFB53B" },
  { name: "Dorado Satín", hex: "#CBA135" },
  { name: "Dorado California", hex: "#DCA111" },
  { name: "Dorado Peru", hex: "#CD853F" },
  { name: "Dorado Harvest", hex: "#DA9100" },

  // Verdes
  { name: "Verde", hex: "#008000" },
  { name: "Verde Lima", hex: "#00FF00" },
  { name: "Verde Lima Claro", hex: "#90EE90" },
  { name: "Verde Lima Oscuro", hex: "#32CD32" },
  { name: "Verde Manzana", hex: "#8DB600" },
  { name: "Verde Esmeralda", hex: "#50C878" },
  { name: "Verde Esmeralda Oscuro", hex: "#046307" },
  { name: "Verde Bosque", hex: "#228B22" },
  { name: "Verde Bosque Oscuro", hex: "#006400" },
  { name: "Verde Mar", hex: "#2E8B57" },
  { name: "Verde Mar Medio", hex: "#3CB371" },
  { name: "Verde Mar Oscuro", hex: "#8FBC8F" },
  { name: "Verde Oliva", hex: "#808000" },
  { name: "Verde Oliva Oscuro", hex: "#556B2F" },
  { name: "Verde Oliva Claro", hex: "#6B8E23" },
  { name: "Verde Militar", hex: "#6B8E23" },
  { name: "Verde Cazador", hex: "#355E3B" },
  { name: "Verde Pino", hex: "#01796F" },
  { name: "Verde Jade", hex: "#00A86B" },
  { name: "Verde Menta", hex: "#98FF98" },
  { name: "Verde Menta Claro", hex: "#F5FFFA" },
  { name: "Verde Primavera", hex: "#00FF7F" },
  { name: "Verde Primavera Medio", hex: "#00FA9A" },
  { name: "Verde Chartreuse", hex: "#7FFF00" },
  { name: "Verde Chartreuse Amarillo", hex: "#DFFF00" },
  { name: "Verde Prado", hex: "#87D300" },
  { name: "Verde Amazonas", hex: "#3B7A57" },
  { name: "Verde Británico", hex: "#004225" },
  { name: "Verde Brunswick", hex: "#1B4D3E" },
  { name: "Verde Cadmio", hex: "#006B3C" },
  { name: "Verde Celadón", hex: "#ACE1AF" },
  { name: "Verde Dartmouth", hex: "#00703C" },
  { name: "Verde Hooker", hex: "#49796B" },
  { name: "Verde India", hex: "#138808" },
  { name: "Verde Islam", hex: "#009000" },
  { name: "Verde Kelly", hex: "#4CBB17" },
  { name: "Verde Malachita", hex: "#0BDA51" },
  { name: "Verde Musgo", hex: "#8A9A5B" },
  { name: "Verde NDHU", hex: "#007B33" },
  { name: "Verde Pakistan", hex: "#006600" },
  { name: "Verde Paris", hex: "#50C878" },
  { name: "Verde Persian", hex: "#00A693" },
  { name: "Verde Ruso", hex: "#679267" },
  { name: "Verde Sacramento", hex: "#043927" },
  { name: "Verde SAP", hex: "#008FD3" },
  { name: "Verde Tea", hex: "#D0F0C0" },
  { name: "Verde Turquesa", hex: "#A0D6B4" },
  { name: "Verde Verdigris", hex: "#43B3AE" },
  { name: "Verde Zomp", hex: "#39A78E" },

  // Azules
  { name: "Azul", hex: "#0000FF" },
  { name: "Azul Claro", hex: "#ADD8E6" },
  { name: "Azul Polvo", hex: "#B0E0E6" },
  { name: "Azul Cielo", hex: "#87CEEB" },
  { name: "Azul Cielo Profundo", hex: "#00BFFF" },
  { name: "Azul Acero", hex: "#4682B4" },
  { name: "Azul Acero Claro", hex: "#B0C4DE" },
  { name: "Azul Dodger", hex: "#1E90FF" },
  { name: "Azul Medianoche", hex: "#191970" },
  { name: "Azul Marino", hex: "#000080" },
  { name: "Azul Oscuro", hex: "#00008B" },
  { name: "Azul Real", hex: "#4169E1" },
  { name: "Azul Nave", hex: "#000080" },
  { name: "Azul Cerúleo", hex: "#007BA7" },
  { name: "Azul Cerúleo Oscuro", hex: "#08457E" },
  { name: "Azul Cobalto", hex: "#0047AB" },
  { name: "Azul Maya", hex: "#73C2FB" },
  { name: "Azul Púrpura", hex: "#8A2BE2" },
  { name: "Azul Zafiro", hex: "#0F52BA" },
  { name: "Azul Zafiro Medio", hex: "#0067A5" },
  { name: "Azul Turquesa", hex: "#40E0D0" },
  { name: "Azul Turquesa Oscuro", hex: "#00CED1" },
  { name: "Azul Turquesa Medio", hex: "#48D1CC" },
  { name: "Azul Turquesa Pálido", hex: "#AFEEEE" },
  { name: "Azul Alice", hex: "#F0F8FF" },
  { name: "Azul Cadete", hex: "#5F9EA0" },
  { name: "Azul Cornflower", hex: "#6495ED" },
  { name: "Azul Denim", hex: "#1560BD" },
  { name: "Azul Duke", hex: "#00009C" },
  { name: "Azul Egipcio", hex: "#1034A6" },
  { name: "Azul Federal", hex: "#002B7F" },
  { name: "Azul Gracia", hex: "#007DFF" },
  { name: "Azul Internacional Klein", hex: "#002FA7" },
  { name: "Azul Iris", hex: "#5A4FCF" },
  { name: "Azul Lapislázuli", hex: "#26619C" },
  { name: "Azul Libertad", hex: "#545AA7" },
  { name: "Azul Oxford", hex: "#002147" },
  { name: "Azul Palacio", hex: "#302B54" },
  { name: "Azul Persa", hex: "#1C39BB" },
  { name: "Azul Prusia", hex: "#003153" },
  { name: "Azul UCLA", hex: "#536895" },
  { name: "Azul Yale", hex: "#00356B" },
  { name: "Azul Bondi", hex: "#0095B6" },
  { name: "Azul Carolina", hex: "#56A0D3" },
  { name: "Azul Celeste", hex: "#B2FFFF" },
  { name: "Azul Columbia", hex: "#9BDDFF" },
  { name: "Azul NCS", hex: "#0087BD" },
  { name: "Azul Pacific", hex: "#1CA9C9" },
  { name: "Azul Tiffany", hex: "#81D8D0" },
  { name: "Azul True", hex: "#0073CF" },
  { name: "Azul TU", hex: "#0039A6" },

  // Morados, Violetas y Púrpuras
  { name: "Púrpura", hex: "#800080" },
  { name: "Púrpura Oscuro", hex: "#4B0082" },
  { name: "Púrpura Medio", hex: "#9370DB" },
  { name: "Púrpura Pálido", hex: "#DDA0DD" },
  { name: "Púrpura Orquídea", hex: "#DA70D6" },
  { name: "Púrpura Ciruela", hex: "#DDA0DD" },
  { name: "Violeta", hex: "#8F00FF" },
  { name: "Violeta Oscuro", hex: "#9400D3" },
  { name: "Violeta Azul", hex: "#8A2BE2" },
  { name: "Violeta Claro", hex: "#EE82EE" },
  { name: "Violeta Pálido", hex: "#CC99FF" },
  { name: "Índigo", hex: "#4B0082" },
  { name: "Índigo Eléctrico", hex: "#6F00FF" },
  { name: "Índigo Persa", hex: "#32127A" },
  { name: "Lavanda", hex: "#E6E6FA" },
  { name: "Lavanda Azul", hex: "#CCCCFF" },
  { name: "Lavanda Flor", hex: "#B57EDC" },
  { name: "Lavanda Gris", hex: "#C4C3D0" },
  { name: "Lavanda Rosa", hex: "#FFF0F5" },
  { name: "Malva", hex: "#E0B0FF" },
  { name: "Malva Claro", hex: "#DCD0FF" },
  { name: "Malva Oscuro", hex: "#9966CC" },
  { name: "Morado", hex: "#6A0DAD" },
  { name: "Morado Byzantino", hex: "#702963" },
  { name: "Morado Imperial", hex: "#602F6B" },
  { name: "Morado Tyrian", hex: "#66023C" },
  { name: "Morado Verónica", hex: "#A020F0" },
  { name: "Amatista", hex: "#9966CC" },
  { name: "Amatista Medio", hex: "#673147" },
  { name: "Heliotropo", hex: "#DF73FF" },
  { name: "Jacinto", hex: "#4B0082" },
  { name: "Lila", hex: "#C8A2C8" },
  { name: "Mauve", hex: "#E0B0FF" },
  { name: "Pervinca", hex: "#CCCCFF" },
  { name: "Uva", hex: "#6F2DA8" },

  // Marrones y Tierras
  { name: "Marrón", hex: "#A52A2A" },
  { name: "Marrón Claro", hex: "#CD853F" },
  { name: "Marrón Oscuro", hex: "#654321" },
  { name: "Marrón Arena", hex: "#F4A460" },
  { name: "Marrón Cuero", hex: "#8B4513" },
  { name: "Marrón Silla de Montar", hex: "#8B4513" },
  { name: "Marrón Peru", hex: "#CD853F" },
  { name: "Marrón Tostado", hex: "#D2B48C" },
  { name: "Marrón Madera", hex: "#C19A6B" },
  { name: "Marrón Caqui", hex: "#C3B091" },
  { name: "Marrón Café", hex: "#6F4E37" },
  { name: "Marrón Caramelo", hex: "#AF6E4D" },
  { name: "Marrón Castaño", hex: "#954535" },
  { name: "Marrón Chocolate", hex: "#7B3F00" },
  { name: "Marrón Cobre", hex: "#B87333" },
  { name: "Marrón Cordobán", hex: "#592720" },
  { name: "Marrón Desert", hex: "#C19A6B" },
  { name: "Marrón Fallow", hex: "#C19A6B" },
  { name: "Marrón Field", hex: "#6C541E" },
  { name: "Marrón Fulvous", hex: "#E48400" },
  { name: "Marrón Kobicha", hex: "#6B4423" },
  { name: "Marrón Russet", hex: "#80461B" },
  { name: "Marrón Sable", hex: "#543F32" },
  { name: "Marrón Sandy", hex: "#F4A460" },
  { name: "Marrón Smokey Topaz", hex: "#832A0D" },
  { name: "Marrón Tan", hex: "#D2B48C" },
  { name: "Marrón Taupe", hex: "#483C32" },
  { name: "Marrón Wenge", hex: "#645452" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Beige Claro", hex: "#F5F5DC" },
  { name: "Beige Oscuro", hex: "#9F8170" },
  { name: "Beige Mode", hex: "#967117" },
  { name: "Beige French", hex: "#A67B5B" },
  { name: "Beige Cos", hex: "#FFF8DC" },
  { name: "Beige Desert", hex: "#FAD5A5" },
  { name: "Beige Ecru", hex: "#C2B280" },
  { name: "Beige Khaki", hex: "#F0E68C" },
  { name: "Beige Parchment", hex: "#F1E9D2" },
  { name: "Beige Vanilla", hex: "#F3E5AB" },
  { name: "Bronce", hex: "#CD7F32" },
  { name: "Bronce Antiguo", hex: "#8C7853" },
  { name: "Cobre", hex: "#B87333" },
  { name: "Cobre Penny", hex: "#AD6F69" },
  { name: "Cobre Rosado", hex: "#B87333" },
  { name: "Latón", hex: "#B5A642" },
  { name: "Ocre", hex: "#CC7722" },
  { name: "Ocre Amarillo", hex: "#CC7722" },
  { name: "Ocre Rojo", hex: "#913831" },
  { name: "Siena", hex: "#A0522D" },
  { name: "Siena Quemado", hex: "#8A3324" },
  { name: "Siena Natural", hex: "#A0522D" },
  { name: "Tierra Sombra", hex: "#8A3324" },
  { name: "Tierra Sombra Quemada", hex: "#8A3324" },
  { name: "Umber", hex: "#635147" },
  { name: "Umber Quemado", hex: "#8A3324" },
  { name: "Sepia", hex: "#704214" },
  { name: "Tostado", hex: "#D2B48C" },
  { name: "Almendra", hex: "#EFDECD" },
  { name: "Avellana", hex: "#A52A2A" },
  { name: "Cacahuate", hex: "#782F16" },
  { name: "Café", hex: "#6F4E37" },
  { name: "Canela", hex: "#D2691E" },
  { name: "Caramelo", hex: "#AF6E4D" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Chocolate Oscuro", hex: "#5C3317" },
  { name: "Chocolate Caliente", hex: "#6B4423" },
  { name: "Coco", hex: "#965A3E" },
  { name: "Miel", hex: "#F0FFF0" },
  { name: "Miel Oscuro", hex: "#B8860B" },
  { name: "Nogal", hex: "#773F1A" },
  { name: "Nuez", hex: "#773F1A" },
  { name: "Vainilla", hex: "#F3E5AB" },

  // Pasteles y Suaves
  { name: "Pastel Azul", hex: "#AEC6CF" },
  { name: "Pastel Verde", hex: "#77DD77" },
  { name: "Pastel Rosa", hex: "#FFD1DC" },
  { name: "Pastel Amarillo", hex: "#FDFD96" },
  { name: "Pastel Naranja", hex: "#FFB347" },
  { name: "Pastel Púrpura", hex: "#B39EB5" },
  { name: "Pastel Marrón", hex: "#836953" },
  { name: "Pastel Gris", hex: "#CFCFC4" },
  { name: "Pastel Lavanda", hex: "#DCD0FF" },
  { name: "Pastel Melocotón", hex: "#FFDAB9" },
  { name: "Pastel Menta", hex: "#BDFCC9" },
  { name: "Suave Rosa", hex: "#FFB6C1" },
  { name: "Suave Azul", hex: "#89CFF0" },
  { name: "Suave Verde", hex: "#90EE90" },
  { name: "Suave Amarillo", hex: "#FFFFE0" },
  { name: "Suave Lavanda", hex: "#E6E6FA" },
  { name: "Suave Coral", hex: "#F08080" },
  { name: "Suave Melocotón", hex: "#FFDAB9" },
  { name: "Suave Menta", hex: "#98FB98" },

  // Metálicos y Especiales
  { name: "Plata", hex: "#C0C0C0" },
  { name: "Plata Antiguo", hex: "#C0C0C0" },
  { name: "Plata Británico", hex: "#C0C0C0" },
  { name: "Oro Rosa", hex: "#E6BE8A" },
  { name: "Oro Blanco", hex: "#FFFDD0" },
  { name: "Oro Amarillo", hex: "#FFD700" },
  { name: "Bronceado", hex: "#CD7F32" },
  { name: "Cobre Metálico", hex: "#B87333" },
  { name: "Latón Metálico", hex: "#B5A642" },
  { name: "Acero", hex: "#4682B4" },
  { name: "Acero Inoxidable", hex: "#E0DFDB" },
  { name: "Hierro", hex: "#5A5A5A" },
  { name: "Níquel", hex: "#727272" },
  { name: "Cromo", hex: "#D4D4D4" },
  { name: "Aluminio", hex: "#848789" },
  { name: "Estaño", hex: "#7F7F7F" },
  { name: "Plomo", hex: "#2F4F4F" },
  { name: "Mercurio", hex: "#E5E5E5" },
  { name: "Zinc", hex: "#7F7F7F" },
  { name: "Titanio", hex: "#878681" },
  { name: "Wolframio", hex: "#5A5A5A" },

  // Colores de Piedras Preciosas
  { name: "Ámbar", hex: "#FFBF00" },
  { name: "Ámbar Azul", hex: "#6CDAE7" },
  { name: "Ámbar Rosa", hex: "#FF33CC" },
  { name: "Ámbar Verde", hex: "#8A9A5B" },
  { name: "Amatista", hex: "#9966CC" },
  { name: "Amatista Oscuro", hex: "#6C3082" },
  { name: "Berilo", hex: "#DCE5E2" },
  { name: "Berilo Dorado", hex: "#F0E68C" },
  { name: "Berilo Verde", hex: "#87A96B" },
  { name: "Citrino", hex: "#E4D00A" },
  { name: "Cornalina", hex: "#B31B1B" },
  { name: "Crisoberilo", hex: "#C19A6B" },
  { name: "Cuarzo", hex: "#51484F" },
  { name: "Cuarzo Rosa", hex: "#AA98A9" },
  { name: "Cuarzo Ahumado", hex: "#573B4D" },
  { name: "Diamante", hex: "#B9F2FF" },
  { name: "Esmeralda", hex: "#50C878" },
  { name: "Esmeralda Oscuro", hex: "#046307" },
  { name: "Granate", hex: "#733635" },
  { name: "Jade", hex: "#00A86B" },
  { name: "Jade Oscuro", hex: "#006B3C" },
  { name: "Jaspe", hex: "#D73B3E" },
  { name: "Lapislázuli", hex: "#26619C" },
  { name: "Malaquita", hex: "#0BDA51" },
  { name: "Ónix", hex: "#353839" },
  { name: "Ópalo", hex: "#A8C3BC" },
  { name: "Perla", hex: "#FDEEF4" },
  { name: "Perla Negra", hex: "#1F262A" },
  { name: "Rubí", hex: "#E0115F" },
  { name: "Rubí Oscuro", hex: "#9B111E" },
  { name: "Safiro", hex: "#0F52BA" },
  { name: "Safiro Amarillo", hex: "#F0E68C" },
  { name: "Safiro Rosa", hex: "#FF66CC" },
  { name: "Safiro Verde", hex: "#2E8B57" },
  { name: "Topacio", hex: "#FFC87C" },
  { name: "Topacio Azul", hex: "#6CDAE7" },
  { name: "Topacio Imperial", hex: "#FFB347" },
  { name: "Turquesa", hex: "#40E0D0" },
  { name: "Turquesa Oscuro", hex: "#00CED1" },
  { name: "Zafiro", hex: "#0F52BA" },
  { name: "Zafiro Estrella", hex: "#0F52BA" },

  // Colores de Flores
  { name: "Rosa Flor", hex: "#FF66CC" },
  { name: "Lila Flor", hex: "#C8A2C8" },
  { name: "Orquídea", hex: "#DA70D6" },
  { name: "Orquídea Oscuro", hex: "#9932CC" },
  { name: "Orquídea Medio", hex: "#BA55D3" },
  { name: "Jazmín", hex: "#F8DE7E" },
  { name: "Lavanda Flor", hex: "#B57EDC" },
  { name: "Margarita", hex: "#FFF8DC" },
  { name: "Girasol", hex: "#FFDA03" },
  { name: "Tulipán", hex: "#FF878D" },
  { name: "Violeta Flor", hex: "#8F00FF" },
  { name: "Clavel", hex: "#FFA6C9" },
  { name: "Crisantemo", hex: "#FFD700" },
  { name: "Dalía", hex: "#FF6347" },
  { name: "Hortensia", hex: "#6B7F7F" },
  { name: "Iris", hex: "#5A4FCF" },
  { name: "Jacinto", hex: "#4B0082" },
  { name: "Loto", hex: "#E6E6FA" },
  { name: "Magnolia", hex: "#F8F4FF" },
  { name: "Narciso", hex: "#FFFF31" },
  { name: "Pensamiento", hex: "#A32CC4" },
  { name: "Petunia", hex: "#8A2BE2" },
  { name: "Primavera", hex: "#E4ED66" },

  // Colores de Frutas
  { name: "Fresa", hex: "#FC5A8D" },
  { name: "Frambuesa", hex: "#E30B5D" },
  { name: "Arándano", hex: "#4F86F7" },
  { name: "Arándano Rojo", hex: "#DC143C" },
  { name: "Moras", hex: "#6A0DAD" },
  { name: "Cereza", hex: "#DE3163" },
  { name: "Uva Verde", hex: "#C2F732" },
  { name: "Uva Morada", hex: "#6F2DA8" },
  { name: "Uva Roja", hex: "#6F2DA8" },
  { name: "Limón", hex: "#FFF700" },
  { name: "Lima", hex: "#BFFF00" },
  { name: "Naranja", hex: "#FFA500" },
  { name: "Mandarina", hex: "#F28500" },
  { name: "Pomelo", hex: "#FF6B6B" },
  { name: "Kiwi", hex: "#8EE53F" },
  { name: "Mango", hex: "#FF8243" },
  { name: "Papaya", hex: "#FFEFD5" },
  { name: "Piña", hex: "#FEE12B" },
  { name: "Plátano", hex: "#FFE135" },
  { name: "Sandía", hex: "#FC6C85" },
  { name: "Melón", hex: "#FDBCB4" },
  { name: "Coco", hex: "#965A3E" },
  { name: "Aguacate", hex: "#568203" },
  { name: "Granada", hex: "#660000" },
  { name: "Higo", hex: "#592720" },
  { name: "Dátil", hex: "#833D3E" },

  // Colores de Comida y Bebida
  { name: "Chocolate", hex: "#7B3F00" },
  { name: "Chocolate con Leche", hex: "#84563C" },
  { name: "Chocolate Blanco", hex: "#EDE6D6" },
  { name: "Caramelo", hex: "#AF6E4D" },
  { name: "Vainilla", hex: "#F3E5AB" },
  { name: "Canela", hex: "#D2691E" },
  { name: "Miel", hex: "#FFC30B" },
  { name: "Miel Oscuro", hex: "#B8860B" },
  { name: "Azúcar", hex: "#FFFFFF" },
  { name: "Azúcar Moreno", hex: "#AF6E4D" },
  { name: "Café", hex: "#6F4E37" },
  { name: "Café Negro", hex: "#3B2F2F" },
  { name: "Café con Leche", hex: "#A67B5B" },
  { name: "Té", hex: "#B5651D" },
  { name: "Té Verde", hex: "#D0F0C0" },
  { name: "Vino Tinto", hex: "#722F37" },
  { name: "Vino Blanco", hex: "#FFEBCD" },
  { name: "Vino Rosado", hex: "#FFE4E1" },
  { name: "Cerveza", hex: "#F28E1C" },
  { name: "Whisky", hex: "#D2691E" },
  { name: "Ron", hex: "#D2691E" },
  { name: "Vodka", hex: "#FFFFFF" },
  { name: "Ginebra", hex: "#D4E6B3" },
  { name: "Sidra", hex: "#F0E68C" },
  { name: "Champán", hex: "#F7E7CE" },
  { name: "Cóctel", hex: "#FF6B6B" },
  { name: "Smoothie", hex: "#87D300" },
  { name: "Batido", hex: "#FFE4E1" },

  // Colores de Estaciones
  { name: "Primavera Verde", hex: "#00FF7F" },
  { name: "Primavera Amarillo", hex: "#FFF8DC" },
  { name: "Primavera Rosa", hex: "#FFB6C1" },
  { name: "Verano Azul", hex: "#87CEEB" },
  { name: "Verano Amarillo", hex: "#FFD700" },
  { name: "Verano Verde", hex: "#90EE90" },
  { name: "Otoño Naranja", hex: "#FF8C00" },
  { name: "Otoño Rojo", hex: "#FF4500" },
  { name: "Otoño Marrón", hex: "#A52A2A" },
  { name: "Otoño Dorado", hex: "#FFD700" },
  { name: "Invierno Azul", hex: "#4682B4" },
  { name: "Invierno Blanco", hex: "#FFFFFF" },
  { name: "Invierno Gris", hex: "#708090" },
  { name: "Invierno Plata", hex: "#C0C0C0" },

  // Colores Geográficos
  { name: "Amarillo Sahara", hex: "#F0E68C" },
  { name: "Verde Amazonas", hex: "#3B7A57" },
  { name: "Azul Mediterráneo", hex: "#1E90FF" },
  { name: "Azul Caribe", hex: "#1E90FF" },
  { name: "Verde Irlanda", hex: "#40C575" },
  { name: "Azul Grecia", hex: "#1E90FF" },
  { name: "Rojo España", hex: "#AA381E" },
  { name: "Amarillo Italia", hex: "#F0E68C" },
  { name: "Azul Francia", hex: "#0055A4" },
  { name: "Rojo China", hex: "#AA381E" },
  { name: "Verde India", hex: "#138808" },
  { name: "Azul Rusia", hex: "#0039A6" },
  { name: "Rojo Japón", hex: "#BC002D" },
  { name: "Verde Brasil", hex: "#009739" },
  { name: "Azul Australia", hex: "#1E90FF" },
  { name: "Rojo Canadá", hex: "#FF0000" },
  { name: "Azul Estados Unidos", hex: "#3C3B6E" },
  { name: "Rojo México", hex: "#CE1126" },
  { name: "Verde Egipto", hex: "#008000" },
  { name: "Amarillo Desierto", hex: "#F0E68C" },
  { name: "Azul Océano", hex: "#1E90FF" },
  { name: "Verde Montaña", hex: "#228B22" },
  { name: "Marrón Tierra", hex: "#A52A2A" },
  { name: "Gris Roca", hex: "#708090" },
  { name: "Blanco Nieve", hex: "#FFFFFF" },
  { name: "Azul Cielo", hex: "#87CEEB" },
  { name: "Verde Bosque", hex: "#228B22" },
  { name: "Azul Río", hex: "#1E90FF" },
  { name: "Verde Valle", hex: "#90EE90" },
  { name: "Marrón Colina", hex: "#A52A2A" },
  { name: "Gris Volcán", hex: "#696969" },
  { name: "Azul Laguna", hex: "#1E90FF" },
  { name: "Verde Selva", hex: "#228B22" },
  { name: "Amarillo Sabana", hex: "#F0E68C" },
  { name: "Azul Glaciar", hex: "#87CEEB" },
  { name: "Marrón Cañón", hex: "#A52A2A" },
  { name: "Verde Pradera", hex: "#90EE90" },
  { name: "Azul Cascada", hex: "#1E90FF" },
  { name: "Gris Acantilado", hex: "#708090" },
  { name: "Verde Pantano", hex: "#228B22" },
  { name: "Azul Bahía", hex: "#1E90FF" },
  { name: "Marrón Duna", hex: "#A52A2A" },
  { name: "Verde Oasis", hex: "#90EE90" },
  { name: "Azul Fiordo", hex: "#1E90FF" },
  { name: "Gris Mesa", hex: "#708090" },
  { name: "Verde Tundra", hex: "#90EE90" },
  { name: "Azul Arrecife", hex: "#1E90FF" },
  { name: "Marrón Caverna", hex: "#A52A2A" },
  { name: "Verde Manglar", hex: "#228B22" },
  { name: "Azul Estrecho", hex: "#1E90FF" },
  { name: "Gris Pedregal", hex: "#708090" },
  { name: "Verde Alpino", hex: "#90EE90" },
  { name: "Azul Abismo", hex: "#1E90FF" },
  { name: "Marrón Barranco", hex: "#A52A2A" },
  { name: "Verde Taiga", hex: "#228B22" },
  { name: "Azul Atolón", hex: "#1E90FF" },
  { name: "Gris Badlands", hex: "#708090" },
  { name: "Verde Chaparral", hex: "#90EE90" },
  { name: "Azul Estuario", hex: "#1E90FF" },
  { name: "Marrón Meseta", hex: "#A52A2A" },
  { name: "Verde Páramo", hex: "#228B22" },
  { name: "Azul Golfo", hex: "#1E90FF" },
  { name: "Gris Caliza", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Marisma", hex: "#1E90FF" },
  { name: "Marrón Terraza", hex: "#A52A2A" },
  { name: "Verde Veld", hex: "#228B22" },
  { name: "Azul Seno", hex: "#1E90FF" },
  { name: "Gris Granito", hex: "#708090" },
  { name: "Verde Pampa", hex: "#90EE90" },
  { name: "Azul Ensenada", hex: "#1E90FF" },
  { name: "Marrón Loma", hex: "#A52A2A" },
  { name: "Verde Estepa", hex: "#228B22" },
  { name: "Azul Ría", hex: "#1E90FF" },
  { name: "Gris Basalto", hex: "#708090" },
  { name: "Verde Sabanilla", hex: "#90EE90" },
  { name: "Azul Caleta", hex: "#1E90FF" },
  { name: "Marrón Alto", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Rada", hex: "#1E90FF" },
  { name: "Gris Pizarra", hex: "#708090" },
  { name: "Verde Sabinar", hex: "#90EE90" },
  { name: "Azul Ancón", hex: "#1E90FF" },
  { name: "Marrón Cuesta", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Riachuelo", hex: "#1E90FF" },
  { name: "Gris Pórfido", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Arroyo", hex: "#1E90FF" },
  { name: "Marrón Laderas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Torrente", hex: "#1E90FF" },
  { name: "Gris Gneis", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cañada", hex: "#1E90FF" },
  { name: "Marrón Falda", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Quebrada", hex: "#1E90FF" },
  { name: "Gris Esquisto", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Regato", hex: "#1E90FF" },
  { name: "Marrón Vertiente", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Zanja", hex: "#1E90FF" },
  { name: "Gris Mármol", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Acequia", hex: "#1E90FF" },
  { name: "Marrón Talud", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Caz", hex: "#1E90FF" },
  { name: "Gris Cuarcita", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Canal", hex: "#1E90FF" },
  { name: "Marrón Terraplén", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Conducto", hex: "#1E90FF" },
  { name: "Gris Arenisca", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cauce", hex: "#1E90FF" },
  { name: "Marrón Ribazo", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Lecho", hex: "#1E90FF" },
  { name: "Gris Conglomerado", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Madre", hex: "#1E90FF" },
  { name: "Marrón Escarpe", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Alveo", hex: "#1E90FF" },
  { name: "Gris Brecha", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cama", hex: "#1E90FF" },
  { name: "Marrón Declive", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Fondo", hex: "#1E90FF" },
  { name: "Gris Toba", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Subsuelo", hex: "#1E90FF" },
  { name: "Marrón Pendiente", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Profundidad", hex: "#1E90FF" },
  { name: "Gris Travertino", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Hondura", hex: "#1E90FF" },
  { name: "Marrón Inclinación", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Hondonada", hex: "#1E90FF" },
  { name: "Gris Alabastro", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Sima", hex: "#1E90FF" },
  { name: "Marrón Gradiente", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Abismo", hex: "#1E90FF" },
  { name: "Gris Serpentina", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Precipicio", hex: "#1E90FF" },
  { name: "Marrón Rampa", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Desfiladero", hex: "#1E90FF" },
  { name: "Gris Gabro", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Garganta", hex: "#1E90FF" },
  { name: "Marrón Escalera", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Quiebra", hex: "#1E90FF" },
  { name: "Gris Diorita", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Grieta", hex: "#1E90FF" },
  { name: "Marrón Riscos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Falla", hex: "#1E90FF" },
  { name: "Gris Andesita", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Fractura", hex: "#1E90FF" },
  { name: "Marrón Peñasco", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Hendidura", hex: "#1E90FF" },
  { name: "Gris Riolita", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Resquicio", hex: "#1E90FF" },
  { name: "Marrón Farallón", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Abertura", hex: "#1E90FF" },
  { name: "Gris Obsidiana", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Rendija", hex: "#1E90FF" },
  { name: "Marrón Promontorio", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Fisura", hex: "#1E90FF" },
  { name: "Gris Piedra Pómez", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Ranura", hex: "#1E90FF" },
  { name: "Marrón Alcor", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Surco", hex: "#1E90FF" },
  { name: "Gris Toba Volcánica", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Canalón", hex: "#1E90FF" },
  { name: "Marrón Otero", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Carcavón", hex: "#1E90FF" },
  { name: "Gris Escoria", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Socavón", hex: "#1E90FF" },
  { name: "Marrón Altiplanicie", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Hoya", hex: "#1E90FF" },
  { name: "Gris Lapilli", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Dolina", hex: "#1E90FF" },
  { name: "Marrón Planalto", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Poljé", hex: "#1E90FF" },
  { name: "Gris Ceniza Volcánica", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Uvala", hex: "#1E90FF" },
  { name: "Marrón Altillanura", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Sumidero", hex: "#1E90FF" },
  { name: "Gris Bombas Volcánicas", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cenote", hex: "#1E90FF" },
  { name: "Marrón Páramo", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Gruta", hex: "#1E90FF" },
  { name: "Gris Lava", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cueva", hex: "#1E90FF" },
  { name: "Marrón Altiplano", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Caverna", hex: "#1E90FF" },
  { name: "Gris Magma", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Antro", hex: "#1E90FF" },
  { name: "Marrón Planicie", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Covacha", hex: "#1E90FF" },
  { name: "Gris Roca Ígnea", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Alcornoque", hex: "#1E90FF" },
  { name: "Marrón Llanura", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Refugio", hex: "#1E90FF" },
  { name: "Gris Roca Metamórfica", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cobijo", hex: "#1E90FF" },
  { name: "Marrón Vega", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Guarida", hex: "#1E90FF" },
  { name: "Gris Roca Sedimentaria", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Madriguera", hex: "#1E90FF" },
  { name: "Marrón Campiña", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Nido", hex: "#1E90FF" },
  { name: "Gris Mineral", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Escondrijo", hex: "#1E90FF" },
  { name: "Marrón Dehesa", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Recoveco", hex: "#1E90FF" },
  { name: "Gris Cristal", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Rincón", hex: "#1E90FF" },
  { name: "Marrón Pradería", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Angosto", hex: "#1E90FF" },
  { name: "Gris Gemas", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Estrecho", hex: "#1E90FF" },
  { name: "Marrón Herbazal", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Paso", hex: "#1E90FF" },
  { name: "Gris Rocas", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Portillo", hex: "#1E90FF" },
  { name: "Marrón Pastizal", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Collado", hex: "#1E90FF" },
  { name: "Gris Cantos", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Puerto", hex: "#1E90FF" },
  { name: "Marrón Gramadal", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Abra", hex: "#1E90FF" },
  { name: "Gris Guijarros", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Boquete", hex: "#1E90FF" },
  { name: "Marrón Césped", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Despeñadero", hex: "#1E90FF" },
  { name: "Gris Grava", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Barranco", hex: "#1E90FF" },
  { name: "Marrón Hierba", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Cañón", hex: "#1E90FF" },
  { name: "Gris Arena", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Garganta", hex: "#1E90FF" },
  { name: "Marrón Forraje", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Quebrada", hex: "#1E90FF" },
  { name: "Gris Polvo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Torrente", hex: "#1E90FF" },
  { name: "Marrón Rastrojo", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Arroyo", hex: "#1E90FF" },
  { name: "Gris Tierra", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Riachuelo", hex: "#1E90FF" },
  { name: "Marrón Heno", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Reguero", hex: "#1E90FF" },
  { name: "Gris Barro", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Venas", hex: "#1E90FF" },
  { name: "Marrón Paja", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Hilos", hex: "#1E90FF" },
  { name: "Gris Lodo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Hebras", hex: "#1E90FF" },
  { name: "Marrón Rastrojo", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Filamentos", hex: "#1E90FF" },
  { name: "Gris Cieno", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cordones", hex: "#1E90FF" },
  { name: "Marrón Zacate", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Trenzas", hex: "#1E90FF" },
  { name: "Gris Fango", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cables", hex: "#1E90FF" },
  { name: "Marrón Pasto", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Tubos", hex: "#1E90FF" },
  { name: "Gris Limo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Conductos", hex: "#1E90FF" },
  { name: "Marrón Grama", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Canales", hex: "#1E90FF" },
  { name: "Gris Sedimento", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Tuberías", hex: "#1E90FF" },
  { name: "Marrón Yerba", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Ductos", hex: "#1E90FF" },
  { name: "Gris Aluvión", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Vías", hex: "#1E90FF" },
  { name: "Marrón Vegetación", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Rutas", hex: "#1E90FF" },
  { name: "Gris Depósito", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Senderos", hex: "#1E90FF" },
  { name: "Marrón Flora", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Caminos", hex: "#1E90FF" },
  { name: "Gris Acumulación", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Trazados", hex: "#1E90FF" },
  { name: "Marrón Plantas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Recorridos", hex: "#1E90FF" },
  { name: "Gris Estrato", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Itinerarios", hex: "#1E90FF" },
  { name: "Marrón Hojas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Rutas", hex: "#1E90FF" },
  { name: "Gris Capa", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Veredas", hex: "#1E90FF" },
  { name: "Marrón Tallos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Atajos", hex: "#1E90FF" },
  { name: "Gris Nivel", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Pasajes", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Corredores", hex: "#1E90FF" },
  { name: "Gris Horizonte", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Galerías", hex: "#1E90FF" },
  { name: "Marrón Semillas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Túneles", hex: "#1E90FF" },
  { name: "Gris Perfil", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Pasadizos", hex: "#1E90FF" },
  { name: "Marrón Frutos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Subterráneos", hex: "#1E90FF" },
  { name: "Gris Contorno", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Sótanos", hex: "#1E90FF" },
  { name: "Marrón Bayas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Criptas", hex: "#1E90FF" },
  { name: "Gris Silueta", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Catacumbas", hex: "#1E90FF" },
  { name: "Marrón Nueces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Hipogeos", hex: "#1E90FF" },
  { name: "Gris Figura", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Sepulcros", hex: "#1E90FF" },
  { name: "Marrón Granos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Tumbas", hex: "#1E90FF" },
  { name: "Gris Forma", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Mausoleos", hex: "#1E90FF" },
  { name: "Marrón Legumbres", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Panteones", hex: "#1E90FF" },
  { name: "Gris Estructura", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cementerios", hex: "#1E90FF" },
  { name: "Marrón Verduras", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Necrópolis", hex: "#1E90FF" },
  { name: "Gris Arquitectura", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Camposanto", hex: "#1E90FF" },
  { name: "Marrón Hortalizas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Memorial", hex: "#1E90FF" },
  { name: "Gris Diseño", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Recuerdo", hex: "#1E90FF" },
  { name: "Marrón Tubérculos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Homenaje", hex: "#1E90FF" },
  { name: "Gris Patrón", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Tributo", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Ofrenda", hex: "#1E90FF" },
  { name: "Gris Modelo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Dedicación", hex: "#1E90FF" },
  { name: "Marrón Bulbos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Consagración", hex: "#1E90FF" },
  { name: "Gris Esquema", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Santificación", hex: "#1E90FF" },
  { name: "Marrón Rizomas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Bendición", hex: "#1E90FF" },
  { name: "Gris Bosquejo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Gracia", hex: "#1E90FF" },
  { name: "Marrón Estolones", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Favor", hex: "#1E90FF" },
  { name: "Gris Trazo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Merced", hex: "#1E90FF" },
  { name: "Marrón Cormos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Don", hex: "#1E90FF" },
  { name: "Gris Línea", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Regalo", hex: "#1E90FF" },
  { name: "Marrón Tubérculos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Obsequio", hex: "#1E90FF" },
  { name: "Gris Rayo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Presente", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Detalle", hex: "#1E90FF" },
  { name: "Gris Trazo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Matiz", hex: "#1E90FF" },
  { name: "Marrón Tallos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Toque", hex: "#1E90FF" },
  { name: "Gris Pincel", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Nota", hex: "#1E90FF" },
  { name: "Marrón Hojas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Acento", hex: "#1E90FF" },
  { name: "Gris Mancha", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Punto", hex: "#1E90FF" },
  { name: "Marrón Flores", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Marca", hex: "#1E90FF" },
  { name: "Gris Sombra", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Señal", hex: "#1E90FF" },
  { name: "Marrón Frutos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Indicación", hex: "#1E90FF" },
  { name: "Gris Reflejo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Guía", hex: "#1E90FF" },
  { name: "Marrón Semillas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Referencia", hex: "#1E90FF" },
  { name: "Gris Brillo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Pista", hex: "#1E90FF" },
  { name: "Marrón Granos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Clave", hex: "#1E90FF" },
  { name: "Gris Luz", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Código", hex: "#1E90FF" },
  { name: "Marrón Legumbres", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Símbolo", hex: "#1E90FF" },
  { name: "Gris Resplandor", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Emblema", hex: "#1E90FF" },
  { name: "Marrón Verduras", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Insignia", hex: "#1E90FF" },
  { name: "Gris Destello", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Estandarte", hex: "#1E90FF" },
  { name: "Marrón Hortalizas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Bandera", hex: "#1E90FF" },
  { name: "Gris Fulgor", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Pendón", hex: "#1E90FF" },
  { name: "Marrón Tubérculos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Gallardete", hex: "#1E90FF" },
  { name: "Gris Resplandor", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Vexilo", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Labaro", hex: "#1E90FF" },
  { name: "Gris Luminiscencia", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Estandarte", hex: "#1E90FF" },
  { name: "Marrón Bulbos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Gonfalón", hex: "#1E90FF" },
  { name: "Gris Fosforescencia", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Oriflama", hex: "#1E90FF" },
  { name: "Marrón Rizomas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Bandera", hex: "#1E90FF" },
  { name: "Gris Incandescencia", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Pabellón", hex: "#1E90FF" },
  { name: "Marrón Estolones", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Enseña", hex: "#1E90FF" },
  { name: "Gris Fluorescencia", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Blasón", hex: "#1E90FF" },
  { name: "Marrón Cormos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Escudo", hex: "#1E90FF" },
  { name: "Gris Irradiación", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Brasón", hex: "#1E90FF" },
  { name: "Marrón Tubérculos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Heráldica", hex: "#1E90FF" },
  { name: "Gris Radiación", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Armas", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Timbre", hex: "#1E90FF" },
  { name: "Gris Emanación", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Cimera", hex: "#1E90FF" },
  { name: "Marrón Tallos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Corona", hex: "#1E90FF" },
  { name: "Gris Efluvio", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Diadema", hex: "#1E90FF" },
  { name: "Marrón Hojas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Aureola", hex: "#1E90FF" },
  { name: "Gris Aura", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Halo", hex: "#1E90FF" },
  { name: "Marrón Flores", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Nimbo", hex: "#1E90FF" },
  { name: "Gris Velo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Gloria", hex: "#1E90FF" },
  { name: "Marrón Frutos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Resplandor", hex: "#1E90FF" },
  { name: "Gris Neblina", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Fulgor", hex: "#1E90FF" },
  { name: "Marrón Semillas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Brillantez", hex: "#1E90FF" },
  { name: "Gris Bruma", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Luminosidad", hex: "#1E90FF" },
  { name: "Marrón Granos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Refulgencia", hex: "#1E90FF" },
  { name: "Gris Niebla", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Esplendor", hex: "#1E90FF" },
  { name: "Marrón Legumbres", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Magnificencia", hex: "#1E90FF" },
  { name: "Gris Vapor", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Fastuosidad", hex: "#1E90FF" },
  { name: "Marrón Verduras", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Suntuosidad", hex: "#1E90FF" },
  { name: "Gris Humo", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Opulencia", hex: "#1E90FF" },
  { name: "Marrón Hortalizas", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Riqueza", hex: "#1E90FF" },
  { name: "Gris Gas", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Abundancia", hex: "#1E90FF" },
  { name: "Marrón Tubérculos", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Prosperidad", hex: "#1E90FF" },
  { name: "Gris Aire", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
  { name: "Azul Fortuna", hex: "#1E90FF" },
  { name: "Marrón Raíces", hex: "#A52A2A" },
  { name: "Verde Sabana", hex: "#228B22" },
  { name: "Azul Ventura", hex: "#1E90FF" },
  { name: "Gris Viento", hex: "#708090" },
  { name: "Verde Sabana", hex: "#90EE90" },
    // --- INICIO DE LA LISTA ADICIONAL DE MÁS DE 600 COLORES ---
  // Puedes copiar todo desde aquí...

  // Grises y Neutros Adicionales
  { name: "Gris Carbón", hex: "#36454F" },
  { name: "Gris Acero Oscuro", hex: "#43464B" },
  { name: "Gris Tundra", hex: "#4A4244" },
  { name: "Gris Ceniza", hex: "#B2BEB5" },
  { name: "Gris Pizarra Medio", hex: "#7E848B" },
  { name: "Gris Perla", hex: "#EAE0C8" },
  { name: "Gris Niebla", hex: "#B0B0B0" },
  { name: "Gris Foca", hex: "#323232" },
  { name: "Gris Topo", hex: "#8B8589" },
  { name: "Gris Guijarro", hex: "#B6B6B4" },
  { name: "Blanco Antiguo", hex: "#FAEBD7" },
  { name: "Blanco Concha", hex: "#FFF5EE" },
  { name: "Blanco Lino", hex: "#FAF0E6" },
  { name: "Blanco Floral", hex: "#FFFAF0" },
  { name: "Blanco Menta", hex: "#F5FFFA" },
  { name: "Blanco Encaje", hex: "#FDF5E6" },
  { name: "Blanco Marfil Oscuro", hex: "#FFFFDE" },
  { name: "Gris Nube", hex: "#DCDCDC" },
  { name: "Gris Humo Claro", hex: "#F0F0F0" },
  { name: "Gris Platino", hex: "#E5E4E2" },
  { name: "Gris Estaño", hex: "#918E85" },
  { name: "Gris Davy", hex: "#555555" },
  { name: "Gris Cadete Oscuro", hex: "#4B535A" },
  { name: "Negro Azabache", hex: "#0A0A0A" },
  { name: "Negro Ónix", hex: "#353839" },
  { name: "Negro Carbón", hex: "#222222" },
  { name: "Negro Medianoche", hex: "#000033" },
  { name: "Gris Sombra", hex: "#8A8A8A" },
  { name: "Gris Pardo", hex: "#5D5954" },
  { name: "Gris Fer", hex: "#6C6C6C" },
  { name: "Gris Mercurio", hex: "#E6E6E6" },
  { name: "Gris Cemento", hex: "#8D8D8D" },
  { name: "Gris Granito", hex: "#676767" },
  { name: "Gris Manatí", hex: "#979AAA" },
  { name: "Gris Roca", hex: "#4D4D4D" },
  { name: "Gris Sincero", hex: "#A9A9A9" },
  { name: "Gris Lobo", hex: "#D1D0CE" },
  { name: "Gris Hongo", hex: "#C2B2A0" },
  { name: "Gris Fósil", hex: "#B5B5B5" },
  { name: "Gris Acorazado", hex: "#848482" },
  { name: "Gris Artillería", hex: "#848b82" },
  { name: "Gris Níquel", hex: "#727472" },
  { name: "Gris Plomo", hex: "#7B7B7B" },
  { name: "Gris Ahumado", hex: "#708090" },
  { name: "Gris Pizarra Azulado", hex: "#6A5ACD" },
  { name: "Blanco Navajo Oscuro", hex: "#FFDAB9" },
  { name: "Blanco Crema", hex: "#FFFDD0" },
  { name: "Blanco Porcelana", hex: "#F0F8FF" },
  { name: "Blanco Nieve", hex: "#FFFAFA" },
  { name: "Blanco Titanio", hex: "#F7F7F7" },
  { name: "Blanco Zinc", hex: "#FCFCFC" },
  { name: "Gris Francés", hex: "#BDBBBD" },
  { name: "Gris Pálido", hex: "#F5F5F5" },
  { name: "Gris Muralla", hex: "#9E9E9E" },
  { name: "Gris Armadillo", hex: "#484A46" },
  { name: "Gris Cadáver", hex: "#CADADC" },
  { name: "Gris Elefante", hex: "#8D918D" },
  { name: "Gris Hierro", hex: "#434343" },
  { name: "Gris Industrial", hex: "#7F7F7F" },
  { name: "Gris Invernal", hex: "#E6E8E8" },
  { name: "Gris Luna", hex: "#C0C0C0" },
  { name: "Gris Metal", hex: "#A7A7A7" },
  { name: "Gris Monzón", hex: "#8A847E" },
  { name: "Gris Ratón", hex: "#9C9C9C" },
  { name: "Gris Sello", hex: "#808080" },
  { name: "Gris Sombra Oscuro", hex: "#5C5C5C" },
  { name: "Gris Urbano", hex: "#B5B5B5" },
  { name: "Gris Vapor", hex: "#D8D8D8" },
  { name: "Gris Volcán", hex: "#5A5A5A" },
  { name: "Gris Zafiro", hex: "#717196" },
  { name: "Gris Zen", hex: "#EAEAEA" },
  { name: "Negro Absoluto", hex: "#000000" },
  { name: "Negro Ébano", hex: "#555D50" },
  { name: "Negro Tinta", hex: "#1C1C1C" },

  // Rojos y Rosados Adicionales
  { name: "Rojo Amapola", hex: "#E35335" },
  { name: "Rojo Borgoña", hex: "#900020" },
  { name: "Rojo Cayena", hex: "#D94E4E" },
  { name: "Rojo Cereza Oscuro", hex: "#D2042D" },
  { name: "Rojo Chianti", hex: "#9C1111" },
  { name: "Rojo Cobre", hex: "#DA8A67" },
  { name: "Rojo Granada", hex: "#B3446C" },
  { name: "Rojo Grosella", hex: "#D21F3C" },
  { name: "Rojo Sangre", hex: "#880808" },
  { name: "Rojo Sangría", hex: "#5D0000" },
  { name: "Rojo Siena Tostado", hex: "#A0522D" },
  { name: "Rojo Tiziano", hex: "#D2691E" },
  { name: "Rojo Veneciano", hex: "#C80815" },
  { name: "Rojo Vino", hex: "#722F37" },
  { name: "Rosa Caramelo", hex: "#FFBCD9" },
  { name: "Rosa Carnación", hex: "#FFA6C9" },
  { name: "Rosa Champán", hex: "#FAD6A5" },
  { name: "Rosa Chicle Oscuro", hex: "#E4717A" },
  { name: "Rosa Coral Claro", hex: "#FFB6B1" },
  { name: "Rosa Cuarzo", hex: "#F7CAC9" },
  { name: "Rosa Flamenco", hex: "#FC8EAC" },
  { name: "Rosa Francés", hex: "#FD3F92" },
  { name: "Rosa Fucsia Claro", hex: "#FFB0FF" },
  { name: "Rosa Geranio", hex: "#F08080" },
  { name: "Rosa Japonés", hex: "#E79F8C" },
  { name: "Rosa Malvavisco", hex: "#FFB6C1" },
  { name: "Rosa Mexicano", hex: "#E4007C" },
  { name: "Rosa Pastel", hex: "#FFD1DC" },
  { name: "Rosa Persa", hex: "#FE28A2" },
  { name: "Rosa Salmón", hex: "#FF91A4" },
  { name: "Rosa Té", hex: "#F4C2C2" },
  { name: "Rosa Viejo", hex: "#C08081" },
  { name: "Rojo Carmín", hex: "#960018" },
  { name: "Rojo Frambuesa", hex: "#E30B5D" },
  { name: "Rojo Geranio", hex: "#E00000" },
  { name: "Rojo Hollywood", hex: "#F4000F" },
  { name: "Rojo Laca", hex: "#D81F2A" },
  { name: "Rojo Mandarín", hex: "#E87400" },
  { name: "Rojo Marrakech", hex: "#7E3B30" },
  { name: "Rojo Marte", hex: "#9E342A" },
  { name: "Rojo Ópalo", hex: "#C73434" },
  { name: "Rojo Pimentón", hex: "#8B0000" },
  { name: "Rojo Pompeya", hex: "#A40000" },
  { name: "Rojo Profundo", hex: "#990000" },
  { name: "Rojo Teja", hex: "#B85A3D" },
  { name: "Rojo Tinta", hex: "#8A0707" },
  { name: "Rojo Toscana", hex: "#7A3A3A" },
  { name: "Rojo Uva", hex: "#8E354A" },
  { name: "Rosa Algodón", hex: "#FFB3C1" },
  { name: "Rosa Azalea", hex: "#F7C3C1" },
  { name: "Rosa Bebé", hex: "#F4C2C2" },
  { name: "Rosa Begonia", hex: "#F7B2B7" },
  { name: "Rosa Brillante", hex: "#FF55A3" },
  { name: "Rosa Cameo", hex: "#EFBBCC" },
  { name: "Rosa Cerezo", hex: "#FFB7C5" },
  { name: "Rosa Concha", hex: "#FDD7E4" },
  { name: "Rosa Crepúsculo", hex: "#FBC1C1" },
  { name: "Rosa Damasco", hex: "#E7A8B8" },
  { name: "Rosa Encanto", hex: "#FBAED2" },
  { name: "Rosa Fantasía", hex: "#FFC0CB" },
  { name: "Rosa Flor", hex: "#FF87B0" },
  { name: "Rosa Fresa", hex: "#FC5A8D" },
  { name: "Rosa Glacial", hex: "#FFDEDE" },
  { name: "Rosa Hollywood", hex: "#FF007F" },
  { name: "Rosa Intenso", hex: "#DE5D83" },
  { name: "Rosa Lavanda Oscuro", hex: "#E1B0E1" },
  { name: "Rosa Neón", hex: "#FF10F0" },
  { name: "Rosa Orquídea Pálido", hex: "#E6B0E6" },
  { name: "Rosa Palo", hex: "#FADADD" },
  { name: "Rosa Perla", hex: "#FBEBE0" },
  { name: "Rosa Primaveral", hex: "#FFB7C5" },
  { name: "Rosa Royal", hex: "#E88EBE" },
  { name: "Rosa Salvaje", hex: "#FD5E53" },
  { name: "Rosa Satén", hex: "#FFD1DC" },
  { name: "Rosa Shocking", hex: "#FC0FC0" },
  { name: "Rosa Suave", hex: "#FDBEBE" },

  // Naranjas y Melocotones Adicionales
  { name: "Naranja Albaricoque", hex: "#FBCEB1" },
  { name: "Naranja Amarillo", hex: "#F8D568" },
  { name: "Naranja Atardecer", hex: "#FD5E53" },
  { name: "Naranja Bronce", hex: "#C87533" },
  { name: "Naranja Calabaza Oscuro", hex: "#E66C2C" },
  { name: "Naranja Caléndula", hex: "#FFC300" },
  { name: "Naranja Clementina", hex: "#F9A03F" },
  { name: "Naranja Fuego", hex: "#E05B00" },
  { name: "Naranja Fuerte", hex: "#FF4500" },
  { name: "Naranja Gamboge", hex: "#E49B0F" },
  { name: "Naranja Kaki", hex: "#F09000" },
  { name: "Naranja Mango", hex: "#FFC300" },
  { name: "Naranja Marigold", hex: "#FCAE1E" },
  { name: "Naranja Neón", hex: "#FF6700" },
  { name: "Naranja Persa", hex: "#D99058" },
  { name: "Naranja Quemado", hex: "#CC5500" },
  { name: "Naranja Real", hex: "#F28C28" },
  { name: "Naranja Tangelo", hex: "#F94D00" },
  { name: "Naranja Tostado", hex: "#C46210" },
  { name: "Naranja Vívido", hex: "#FF5F00" },
  { name: "Naranja Yema", hex: "#FFB000" },
  { name: "Melocotón Brillante", hex: "#FFC3A0" },
  { name: "Melocotón Crema", hex: "#FFF0DB" },
  { name: "Melocotón Pálido", hex: "#FFE5B4" },
  { name: "Melocotón Suave", hex: "#FFDAB9" },
  { name: "Albaricoque Claro", hex: "#FFD5B1" },
  { name: "Ámbar", hex: "#FFBF00" },
  { name: "Cobre", hex: "#B87333" },
  { name: "Durazno Suave", hex: "#FFCBA4" },
  { name: "Mandarin Claro", hex: "#FFD580" },
  { name: "Ocre Naranja", hex: "#F28C28" },
  { name: "Papaya", hex: "#FFC152" },
  { name: "Siena Natural", hex: "#B78A64" },
  { name: "Zanahoria", hex: "#FD6A02" },
  { name: "Naranja Alegría", hex: "#FFAA33" },
  { name: "Naranja Arcilla", hex: "#E3701A" },
  { name: "Naranja Cadmio Oscuro", hex: "#E64D00" },
  { name: "Naranja Calipso", hex: "#FF9A00" },
  { name: "Naranja Canela", hex: "#D2691E" },
  { name: "Naranja Cítrico", hex: "#FF8000" },
  { name: "Naranja Cobrizo", hex: "#D97904" },
  { name: "Naranja Coral Oscuro", hex: "#E06852" },
  { name: "Naranja Crepúsculo", hex: "#ED872D" },
  { name: "Naranja Damasco", hex: "#FFB266" },
  { name: "Naranja Eléctrico", hex: "#FF3300" },
  { name: "Naranja Especia", hex: "#C06527" },
  { name: "Naranja Explosión", hex: "#FF5E0E" },
  { name: "Naranja Festivo", hex: "#FF7518" },
  { name: "Naranja Fogata", hex: "#E25822" },
  { name: "Naranja Fuego Intenso", hex: "#FF4400" },
  { name: "Naranja Jengibre", hex: "#C06527" },
  { name: "Naranja Jugoso", hex: "#FF8C00" },
  { name: "Naranja Lava", hex: "#E62000" },
  { name: "Naranja Luminoso", hex: "#FFAA00" },
  { name: "Naranja Miel", hex: "#FCAE1E" },
  { name: "Naranja Ocaso", hex: "#F28500" },
  { name: "Naranja Óxido", hex: "#B7410E" },
  { name: "Naranja Papaya", hex: "#FFC152" },
  { name: "Naranja Picante", hex: "#FF3300" },
  { name: "Naranja Pimienta", hex: "#D94E1A" },
  { name: "Naranja Radiante", hex: "#FF6600" },
  { name: "Naranja Sol", hex: "#FF8C00" },
  { name: "Naranja Sorbete", hex: "#FF9966" },
  { name: "Naranja Tigre", hex: "#E65C00" },
  { name: "Naranja Tropical", hex: "#FF7700" },
  { name: "Naranja Vibrante", hex: "#FF4500" },
  { name: "Naranja Vitamina", hex: "#FF7518" },
  { name: "Naranja Volcánico", hex: "#E63C00" },
  { name: "Melocotón Dorado", hex: "#FFC380" },
  { name: "Melocotón Néctar", hex: "#FFD0A0" },
  { name: "Melocotón Porcelana", hex: "#FFE5D0" },
  { name: "Melocotón Rosado", hex: "#FFCBA4" },
  { name: "Melocotón Suave", hex: "#FFDAB9" },
  { name: "Melocotón Veraniego", hex: "#FFB07C" },
  { name: "Albaricoque Dorado", hex: "#FFC266" },
  { name: "Albaricoque Seco", hex: "#D99058" },
  { name: "Albaricoque Suave", hex: "#FFE0C0" },
  { name: "Tangerina", hex: "#F28500" },
  { name: "Tangerina Fuerte", hex: "#FF4500" },

  // Amarillos y Dorados Adicionales
  { name: "Amarillo Ácido", hex: "#DFFF00" },
  { name: "Amarillo Ambarino", hex: "#FFBF00" },
  { name: "Amarillo Banana", hex: "#FFE135" },
  { name: "Amarillo Cadmio", hex: "#FFF600" },
  { name: "Amarillo Canario", hex: "#FFFF99" },
  { name: "Amarillo Chartreuse", hex: "#DFFF00" },
  { name: "Amarillo Crema", hex: "#FFFDD0" },
  { name: "Amarillo Cromo", hex: "#FFAA00" },
  { name: "Amarillo Diente de León", hex: "#F0E130" },
  { name: "Amarillo Dólar", hex: "#E1C16E" },
  { name: "Amarillo Dorado", hex: "#FFCC00" },
  { name: "Amarillo Eléctrico", hex: "#FFFF33" },
  { name: "Amarillo Fluorescente", hex: "#CCFF00" },
  { name: "Amarillo Girasol", hex: "#FFC30B" },
  { name: "Amarillo Huevo", hex: "#F2D750" },
  { name: "Amarillo Láser", hex: "#FFFF66" },
  { name: "Amarillo Lima", hex: "#CCFF00" },
  { name: "Amarillo Maíz", hex: "#FBEC5D" },
  { name: "Amarillo Mantequilla", hex: "#FFFF80" },
  { name: "Amarillo Neón", hex: "#FFFF00" },
  { name: "Amarillo Ocaso", hex: "#F3C13A" },
  { name: "Amarillo Oro", hex: "#FFD700" },
  { name: "Amarillo Paja", hex: "#E4D96F" },
  { name: "Amarillo Piña", hex: "#FEE12B" },
  { name: "Amarillo Pollito", hex: "#FFFFAA" },
  { name: "Amarillo Real", hex: "#FADA5E" },
  { name: "Amarillo Sol", hex: "#FFD800" },
  { name: "Amarillo Trigo", hex: "#F5DEB3" },
  { name: "Amarillo Vainilla", hex: "#F3E5AB" },
  { name: "Dorado Antiguo", hex: "#C0A062" },
  { name: "Dorado Arena", hex: "#F0DC82" },
  { name: "Dorado Bronce", hex: "#CD7F32" },
  { name: "Dorado Champaña", hex: "#F7E7CE" },
  { name: "Dorado Cobre", hex: "#DA8A67" },
  { name: "Dorado Pálido", hex: "#EEE8AA" },
  { name: "Dorado Rosado", hex: "#E6BE8A" },
  { name: "Dorado Sahára", hex: "#F0E68C" },
  { name: "Amarillo Abeja", hex: "#FFC30B" },
  { name: "Amarillo Azafrán", hex: "#F4C430" },
  { name: "Amarillo Brillante", hex: "#FFFF00" },
  { name: "Amarillo Cadmio Limón", hex: "#FFFF33" },
  { name: "Amarillo Caléndula", hex: "#FFC300" },
  { name: "Amarillo Celeste", hex: "#FFFF99" },
  { name: "Amarillo Citrino", hex: "#E4D00A" },
  { name: "Amarillo Colza", hex: "#FBEC5D" },
  { name: "Amarillo Cosmos", hex: "#FFD800" },
  { name: "Amarillo Cúrcuma", hex: "#FCAE1E" },
  { name: "Amarillo de Indias", hex: "#E3A857" },
  { name: "Amarillo Desierto", hex: "#EDC9AF" },
  { name: "Amarillo Energético", hex: "#F7E800" },
  { name: "Amarillo Escolar", hex: "#FFD800" },
  { name: "Amarillo Especiado", hex: "#F2D750" },
  { name: "Amarillo Estelar", hex: "#FFFC33" },
  { name: "Amarillo Genista", hex: "#F0E130" },
  { name: "Amarillo Intenso", hex: "#FFD700" },
  { name: "Amarillo Jonquil", hex: "#FADA5E" },
  { name: "Amarillo Jubiloso", hex: "#FCEE21" },
  { name: "Amarillo Limonada", hex: "#FFFFAA" },
  { name: "Amarillo Luminoso", hex: "#FFFF00" },
  { name: "Amarillo Madreselva", hex: "#F0E130" },
  { name: "Amarillo Mango", hex: "#FFC300" },
  { name: "Amarillo Mimosa", hex: "#FFF44F" },
  { name: "Amarillo Mostaza Oscuro", hex: "#A88A00" },
  { name: "Amarillo Nápoles", hex: "#FADA5E" },
  { name: "Amarillo Narciso", hex: "#FFFF31" },
  { name: "Amarillo Ocre Dorado", hex: "#E1C16E" },
  { name: "Amarillo Oliva", hex: "#C5C13D" },
  { name: "Amarillo Plátano", hex: "#FFE135" },
  { nameG: "Amarillo Radiante", hex: "#FFD800" },
  { name: "Amarillo Suave", hex: "#FFFFAA" },
  { name: "Amarillo Topacio", hex: "#FFC87C" },
  { name: "Amarillo Tostado", hex: "#F5DEB3" },
  { name: "Amarillo Verde", hex: "#ADFF2F" },
  { name: "Dorado Arena Brillante", hex: "#F0DC82" },
  { name: "Dorado Bizantino", hex: "#BD9B16" },
  { name: "Dorado Cálido", hex: "#E1C16E" },
  { name: "Dorado Ocre", hex: "#C0A062" },
  { name: "Dorado Paja", hex: "#E4D96F" },
  { name: "Dorado Trigo", hex: "#F5DEB3" },
  { name: "Dorado Viejo", hex: "#CFB53B" },
  
  // Verdes Adicionales
  { name: "Verde Abeto", hex: "#016936" },
  { name: "Verde Aguacate", hex: "#568203" },
  { name: "Verde Alga", hex: "#50C878" },
  { name: "Verde Alpino", hex: "#4B5B1E" },
  { name: "Verde Bilis", hex: "#99CC00" },
  { name: "Verde Billar", hex: "#008000" },
  { name: "Verde Botella", hex: "#006A4E" },
  { name: "Verde Brillante", hex: "#66FF00" },
  { name: "Verde Bronce", hex: "#4A412A" },
  { name: "Verde Caqui", hex: "#BDB76B" },
  { name: "Verde Cazador Oscuro", hex: "#2E4638" },
  { name: "Verde Celadón", hex: "#ACE1AF" },
  { name: "Verde Césped", hex: "#7CFC00" },
  { name: "Verde Cian", hex: "#00FFFF" },
  { name: "Verde Citrino", hex: "#DFFF00" },
  { name: "Verde Clorofila", hex: "#008000" },
  { name: "Verde Esmeralda Claro", hex: "#80FF80" },
  { name: "Verde Espárrago", hex: "#87A96B" },
  { name: "Verde Felpa", hex: "#00703C" },
  { name: "Verde Fluorescente", hex: "#00FF00" },
  { name: "Verde Helecho", hex: "#4F7942" },
  { name: "Verde Hooker", hex: "#49796B" },
  { name: "Verde Jade Oscuro", hex: "#00703C" },
  { name: "Verde Jungla", hex: "#29AB87" },
  { name: "Verde Kelly", hex: "#4CBB17" },
  { name: "Verde Laurel", hex: "#A9A9A9" },
  { name: "Verde Lima Eléctrico", hex: "#CCFF00" },
  { name: "Verde Limón", hex: "#BFFF00" },
  { name: "Verde Malva", hex: "#99FF99" },
  { name: "Verde Manzana Ácida", hex: "#BFFF00" },
  { name: "Verde Mar Claro", hex: "#20B2AA" },
  { name: "Verde Menta", hex: "#3EB489" },
  { name: "Verde Menta Crema", hex: "#F5FFFA" },
  { name: "Verde Menta Neón", hex: "#39FF14" },
  { name: "Verde Militar", hex: "#78866B" },
  { name: "Verde Musgo", hex: "#8A9A5B" },
  { name: "Verde Neón", hex: "#39FF14" },
  { name: "Verde Oliva", hex: "#808000" },
  { name: "Verde Oliva Pálido", hex: "#B3B36B" },
  { name: "Verde Oscuro", hex: "#013220" },
  { name: "Verde Pálido", hex: "#98FB98" },
  { name: "Verde Pantano", hex: "#666633" },
  { name: "Verde París", hex: "#50C878" },
  { name: "Verde Pastel", hex: "#77DD77" },
  { name: "Verde Persa", hex: "#00A693" },
  { name: "Verde Pino", hex: "#01796F" },
  { name: "Verde Pistacho", hex: "#93C572" },
  { name: "Verde Pradera", hex: "#50C878" },
  { name: "Verde Profundo", hex: "#005000" },
  { name: "Verde Primavera", hex: "#00FF7F" },
  { name: "Verde Reseda", hex: "#6C7E5C" },
  { name: "Verde Sapo", hex: "#567D46" },
  { name: "Verde Té", hex: "#D0F0C0" },
  { name: "Verde Turquesa", hex: "#A0D6B4" },
  { name: "Verde Veronese", hex: "#408F7H" },
  { name: "Verde Vesubio", hex: "#5C7148" },
  { name: "Verde Victoria", hex: "#4C583E" },
  { name: "Verde Vigía", hex: "#4E5549" },
  { name: "Verde Vintage", hex: "#808060" },
  { name: "Verde Viridián", hex: "#40826D" },
  { name: "Verde Zafiro", hex: "#325149" },
  { name: "Verde Zarcillo", hex: "#80FF00" },
  { name: "Verde Zen", hex: "#C0D0C0" },
  { name: "Verde Zodiaco", hex: "#1C2826" },
  { name: "Verde Zumo", hex: "#A1C500" },
  { name: "Lima Ácida", hex: "#BFFF00" },
  { name: "Lima Eléctrica", hex: "#AEFF00" },
  { name: "Lima Francesa", hex: "#9EFD38" },
  { name: "Lima Key", hex: "#C0FF00" },
  { name: "Lima Voltio", hex: "#CEFF00" },
  { name: "Chartreuse", hex: "#7FFF00" },
  { name: "Chartreuse Neón", hex: "#AFFF00" },
  { name: "Chartreuse Amarillo", hex: "#DFFF00" },

  // Azules Adicionales
  { name: "Azul Aciano", hex: "#6495ED" },
  { name: "Azul Acuarela", hex: "#87CEEB" },
  { name: "Azul Aero", hex: "#7CB9E8" },
  { name: "Azul Agua", hex: "#B0E0E6" },
  { name: "Azul Aguamarina", hex: "#7FFFD4" },
  { name: "Azul Aire", hex: "#A2C4C9" },
  { name: "Azul Ártico", hex: "#C6E6E6" },
  { name: "Azul Báltico", hex: "#2E5A88" },
  { name: "Azul Bebé", hex: "#89CFF0" },
  { name: "Azul Bondi", hex: "#0095B6" },
  { name: "Azul Cadete", hex: "#5F9EA0" },
  { name: "Azul Capitan", hex: "#5F9EA0" },
  { name: "Azul Carolina", hex: "#56A0D3" },
  { name: "Azul Celeste", hex: "#B2FFFF" },
  { name: "Azul Cerúleo", hex: "#007BA7" },
  { name: "Azul Cerúleo Glacial", hex: "#9BC4E2" },
  { name: "Azul Cian", hex: "#00FFFF" },
  { name: "Azul Cian Eléctrico", hex: "#00FFFF" },
  { name: "Azul Cobalto", hex: "#0047AB" },
  { name: "Azul Columbia", hex: "#B9D9EB" },
  { name: "Azul Crepúsculo", hex: "#4F638E" },
  { name: "Azul Danubio", hex: "#6E7F80" },
  { name: "Azul del Rey", hex: "#4169E1" },
  { name: "Azul Denim", hex: "#1560BD" },
  { name: "Azul Eléctrico", hex: "#7DF9FF" },
  { name: "Azul Escarcha", hex: "#E6F7FF" },
  { name: "Azul Espacial", hex: "#1D2951" },
  { name: "Azul Francés", hex: "#0072BB" },
  { name: "Azul Glacial", hex: "#89CFF0" },
  { name: "Azul Hielo", hex: "#E0FFFF" },
  { name: "Azul Imperial", hex: "#002395" },
  { name: "Azul Índigo", hex: "#4B0082" },
  { name: "Azul Infinito", hex: "#002366" },
  { name: "Azul Klein", hex: "#002FA7" },
  { name: "Azul Lapislázuli", hex: "#26619C" },
  { name: "Azul Maya", hex: "#73C2FB" },
  { name: "Azul Mediterráneo", hex: "#1E90FF" },
  { name: "Azul Neón", hex: "#4D4DFF" },
  { name: "Azul Océano", hex: "#1E90FF" },
  { name: "Azul Océano Profundo", hex: "#00538B" },
  { name: "Azul Oxford", hex: "#002147" },
  { name: "Azul Pálido", hex: "#AFEEEE" },
  { name: "Azul Pantalla", hex: "#80C0FF" },
  { name: "Azul Pastel", hex: "#AEC6CF" },
  { name: "Azul Pavo Real", hex: "#33A1C9" },
  { name: "Azul Persa", hex: "#1C39BB" },
  { name: "Azul Petróleo", hex: "#008080" },
  { name: "Azul Picto", hex: "#2A2A7A" },
  { name: "Azul Policía", hex: "#334C66" },
  { name: "Azul Polvo", hex: "#B0E0E6" },
  { name: "Azul Profundo", hex: "#000080" },
  { name: "Azul Prusia", hex: "#003153" },
  { name: "Azul Real Oscuro", hex: "#003366" },
  { name: "Azul Reflex", hex: "#0000FF" },
  { name: "Azul Sagrado", hex: "#00356B" },
  { name: "Azul Savoya", hex: "#4B61D1" },
  { name: "Azul Tinta", hex: "#000080" },
  { name: "Azul Tifany", hex: "#81D8D0" },
  { name: "Azul Topacio", hex: "#77DDE7" },
  { name: "Azul Tormenta", hex: "#6B7A8F" },
  { name: "Azul Ultramar", hex: "#120A8F" },
  { name: "Azul Verdoso", hex: "#234C63" },
  { name: "Azul Vívido", hex: "#1E90FF" },
  { name: "Azul Yale", hex: "#00356B" },
  { name: "Azul Zafiro", hex: "#0F52BA" },
  { name: "Azul Zafiro Oscuro", hex: "#082567" },
  { name: "Cian Claro", hex: "#E0FFFF" },
  { name: "Cian Eléctrico", hex: "#00FFFF" },
  { name: "Cian Oscuro", hex: "#008B8B" },
  { name: "Turquesa", hex: "#40E0D0" },
  { name: "Turquesa Claro", hex: "#AFEEEE" },
  { name: "Turquesa Medio", hex: "#48D1CC" },
  { name: "Turquesa Neón", hex: "#10EFEF" },
  { name: "Turquesa Oscuro", hex: "#00CED1" },

  // Morados, Violetas y Púrpuras Adicionales
  { name: "Morado Amatista", hex: "#9966CC" },
  { name: "Morado Arándano", hex: "#6A0DAD" },
  { name: "Morado Berenjena", hex: "#614051" },
  { name: "Morado Bizantino", hex: "#702963" },
  { name: "Morado Ciruela", hex: "#8E4585" },
  { name: "Morado Eléctrico", hex: "#BF00FF" },
  { name: "Morado Esmerejón", hex: "#5C3C5C" },
  { name: "Morado Flor", hex: "#C71585" },
  { name: "Morado Fucsia", hex: "#C71585" },
  { name: "Morado Heliotropo", hex: "#DF73FF" },
  { name: "Morado Imperial", hex: "#602F6B" },
  { name: "Morado Lavanda", hex: "#B57EDC" },
  { name: "Morado Lila", hex: "#C8A2C8" },
  { name: "Morado Malva", hex: "#E0B0FF" },
  { name: "Morado Medianoche", hex: "#4B0082" },
  { name: "Morado Neón", hex: "#A020F0" },
  { name: "Morado Ocaso", hex: "#8A2BE2" },
  { name: "Morado Orquídea", hex: "#DA70D6" },
  { name: "Morado Pálido", hex: "#DDA0DD" },
  { name: "Morado Pastel", hex: "#B19CD9" },
  { name: "Morado Persa", hex: "#702963" },
  { name: "Morado Profundo", hex: "#800080" },
  { name: "Morado Púrpura", hex: "#800080" },
  { name: "Morado Real", hex: "#7851A9" },
  { name: "Morado Uva", hex: "#6F2DA8" },
  { name: "Morado Violeta", hex: "#8F00FF" },
  { name: "Púrpura Ciruela Oscuro", hex: "#6A0DAD" },
  { name: "Púrpura de Tiro", hex: "#66023C" },
  { name: "Púrpura Eléctrico", hex: "#BF00FF" },
  { name: "Púrpura Escarlata", hex: "#C71585" },
  { name: "Púrpura Fandango", hex: "#B53389" },
  { name: "Púrpura Intenso", hex: "#800080" },
  { name: "Púrpura Lavanda", hex: "#9678B6" },
  { name: "Púrpura Malva", hex: "#D473D4" },
  { name: "Púrpura Medio", hex: "#9370DB" },
  { name: "Púrpura Morado", hex: "#800080" },
  { name: "Púrpura Neón", hex: "#A020F0" },
  { name: "Púrpura Oscuro", hex: "#301934" },
  { name: "Púrpura Pálido", hex: "#DDA0DD" },
  { name: "Púrpura Pastel", hex: "#B19CD9" },
  { name: "Púrpura Pimienta", hex: "#702963" },
  { name: "Púrpura Rojo", hex: "#C71585" },
  { name: "Púrpura Sombra", hex: "#6A0DAD" },
  { name: "Púrpura Verónica", hex: "#A020F0" },
  { name: "Violeta Africano", hex: "#B284BE" },
  { name: "Violeta Azulado", hex: "#8A2BE2" },
  { name: "Violeta Eléctrico", hex: "#8F00FF" },
  { name: "Violeta Escarcha", hex: "#E6E6FA" },
  { name: "Violeta Genciana", hex: "#564064" },
  { name: "Violeta Imperial", hex: "#602F6B" },
  { name: "Violeta Intenso", hex: "#8F00FF" },
  { name: "Violeta Lavanda", hex: "#B57EDC" },
  { name: "Violeta Malva", hex: "#D8BFD8" },
  { name: "Violeta Medio", hex: "#9370DB" },
  { name: "Violeta Neón", hex: "#A020F0" },
  { name: "Violeta Oscuro", hex: "#9400D3" },
  { name: "Violeta Pálido", hex: "#DDA0DD" },
  { name: "Violeta Persa", hex: "#702963" },
  { name: "Violeta Primavera", hex: "#C71585" },
  { name: "Violeta Profundo", hex: "#800080" },
  { name: "Violeta Rojizo", hex: "#C71585" },
  { name: "Violeta Suave", hex: "#E6E6FA" },
  { name: "Lavanda", hex: "#E6E6FA" },
  { name: "Lavanda Azulado", hex: "#B57EDC" },
  { name: "Lavanda Brillante", hex: "#BF94E4" },
  { name: "Lavanda Floral", hex: "#B57EDC" },
  { name: "Lavanda Grisáceo", hex: "#C4C3D0" },
  { name: "Lavanda Pálido", hex: "#DCD0FF" },
  { name: "Lavanda Rosado", hex: "#FBAED2" },
  { name: "Lila", hex: "#C8A2C8" },
  { name: "Lila Pálido", hex: "#DCD0FF" },
  { name: "Lila Rosado", hex: "#E6B0E6" },
  { name: "Lila Suave", hex: "#D8BFD8" },
  { name: "Magenta", hex: "#FF00FF" },
  { name: "Magenta Eléctrico", hex: "#FF00FF" },
  { name: "Magenta Oscuro", hex: "#8B008B" },
  { name: "Magenta Pastel", hex: "#F49AC2" },

  // Marrones y Tierras Adicionales
  { name: "Marrón Arcilla", hex: "#8D5B3A" },
  { name: "Marrón Arena", hex: "#F4A460" },
  { name: "Marrón Avellana", hex: "#AE6840" },
  { name: "Marrón Bizcocho", hex: "#B87333" },
  { name: "Marrón Búfalo", hex: "#BB6528" },
  { name: "Marrón Caoba", hex: "#C04000" },
  { name: "Marrón Café", hex: "#6F4E37" },
  { name: "Marrón Canela", hex: "#D2691E" },
  { name: "Marrón Caramelo", hex: "#C68642" },
  { name: "Marrón Castaño", hex: "#954535" },
  { name: "Marrón Cedro", hex: "#714B23" },
  { name: "Marrón Chocolate", hex: "#7B3F00" },
  { name: "Marrón Ciervo", hex: "#BA8759" },
  { name: "Marrón Coca", hex: "#6F4E37" },
  { name: "Marrón Cognac", hex: "#834333" },
  { name: "Marrón Cuero", hex: "#8B4513" },
  { name: "Marrón Desierto", hex: "#C19A6B" },
  { name: "Marrón Dorado", hex: "#996515" },
  { name: "Marrón Galleta", hex: "#D2B48C" },
  { name: "Marrón Grano", hex: "#6F4E37" },
  { name: "Marrón Jengibre", hex: "#B06500" },
  { name: "Marrón Ladrillo", hex: "#9C462C" },
  { name: "Marrón Madera", hex: "#DEB887" },
  { name: "Marrón Miel", hex: "#C68642" },
  { name: "Marrón Moca", hex: "#5F442C" },
  { name: "Marrón Mostaza", hex: "#C0A062" },
  { name: "Marrón Nuez", hex: "#773F1A" },
  { name: "Marrón Ocre", hex: "#CC7722" },
  { name: "Marrón Óxido", hex: "#B7410E" },
  { name: "Marrón Pardo", hex: "#8B4513" },
  { name: "Marrón Pastel", hex: "#B19CD9" },
  { name: "Marrón Rojizo", hex: "#8B0000" },
  { name: "Marrón Rosado", hex: "#BC8F8F" },
  { name: "Marrón Russet", hex: "#80461B" },
  { name: "Marrón Sahára", hex: "#F0E68C" },
  { name: "Marrón Sepia", hex: "#704214" },
  { name: "Marrón Sombra", hex: "#8A3324" },
  { name: "Marrón Tabaco", hex: "#715D4D" },
  { name: "Marrón Teca", hex: "#808000" },
  { name: "Marrón Tierra", hex: "#A52A2A" },
  { name: "Marrón Topo", hex: "#483C32" },
  { name: "Marrón Trigo", hex: "#F5DEB3" },
  { name: "Marrón Turrón", hex: "#C68642" },
  { name: "Marrón Umber", hex: "#635147" },
  { name: "Marrón Vainilla", hex: "#F3E5AB" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Beige Arena", hex: "#F4A460" },
  { name: "Beige Crema", hex: "#FFFDD0" },
  { name: "Beige Desierto", hex: "#EDC9AF" },
  { name: "Beige Dorado", hex: "#E1C16E" },
  { name: "Beige Grisáceo", hex: "#C2B280" },
  { name: "Beige Hueso", hex: "#F5F5DC" },
  { name: "Beige Lino", hex: "#FAF0E6" },
  { name: "Beige Pálido", hex: "#FFFDD0" },
  { name: "Beige Pergamino", hex: "#F1E9D2" },
  { name: "Beige Rosado", hex: "#FADADD" },
  { name: "Beige Suave", hex: "#F5F5DC" },
  { name: "Beige Trigo", hex: "#F5DEB3" },
  { name: "Beige Vainilla", hex: "#F3E5AB" },
  { name: "Bronce", hex: "#CD7F32" },
  { name: "Bronce Antiguo", hex: "#B8860B" },
  { name: "Bronce Dorado", hex: "#DA8A67" },
  { name: "Bronce Pálido", hex: "#D2B48C" },
  { name: "Bronce Rojizo", hex: "#C87533" },
  { name: "Caqui", hex: "#C3B091" },
  { name: "Caqui Claro", hex: "#F0E68C" },
  { name: "Caqui Oscuro", hex: "#BDB76B" },
  { name: "Caqui Verde", hex: "#808000" },
  { name: "Castaño", hex: "#954535" },
  { name: "Castaño Claro", hex: "#CD853F" },
  { name: "Castaño Oscuro", hex: "#654321" },
  { name: "Castaño Rojizo", hex: "#8B0000" },
  { name: "Siena", hex: "#A0522D" },
  { name: "Siena Tostado", hex: "#8A3324" },
  { name: "Siena Natural", hex: "#B78A64" },
  { name: "Tierra", hex: "#A52A2A" },
  { name: "Tierra Sombra", hex: "#8A3324" },
  { name: "Tierra Sombra Tostada", hex: "#635147" },
  { name: "Topacio Ahumado", hex: "#8B4513" },
  // ... hasta aquí
  // --- FIN DE LA LISTA ADICIONAL ---

];